server:
  port: 9091
  address: 0.0.0.0

spring:
  application:
    name: athena-profile-service
  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: true
        max-connections: 200
        max-connections-per-route: 100
#  openfeign:
#    client:
#      config:
#        athena-report-service:
#          connectTimeout: 160000000
#          readTimeout: 1600000

#logging:
#  level:
#    com.projectathena.userservice.clients.MineWorkerClient: DEBUG
#
#feign:
#  client:
#    config:
#      athena-mine-worker-service:
#          loggerLevel: full

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always